name: food_review
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytest=8.1.1
  - pandas=2.2.1
  - ipykernel=6.29.3 # to run the notebook locally on vscode
  - seaborn=0.13.2
  - textblob=0.18.0.post0
  - scikit-learn=1.4.1.post1
  - xgboost=2.0.3
  - spacy=3.5.3
  - bs4=4.12.2
  - nltk=3.8.1
  - pip
  - pip:
    - contractions