name: CI

on:
  pull_request:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-file: environment.yml
          activate-environment: food_review

      - name: Install dependencies
        run: |
          conda install --file environment.yml
          echo "Make sure your environment.yml already creates and activates the `food_review` environment."

      - name: Run tests
        run: pytest test
